---
- name: Lock down bastion server (monitoring host)
  hosts: monitoring
  become: true
  serial: 1
  vars:
    bastion_host: "{{ groups['monitoring'][0] }}"
    bastion_ip: "{{ hostvars[bastion_host].ansible_host | default(bastion_host) }}"

  tasks:
    - name: Ensure UFW is installed
      package:
        name: ufw
        state: present

    - name: Reset UFW rules
      shell: ufw --force reset

    - name: Set default deny incoming
      ufw:
        direction: incoming
        policy: deny

    - name: Allow outgoing traffic
      ufw:
        direction: outgoing
        policy: allow

    - name: Allow port 80 from anywhere
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow SSH on bastion from anywhere
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled

- name: Wait before continuing to load balancer
  hosts: localhost
  tasks:
    - pause:
        prompt: "Bastion lock-down complete. Press ENTER to continue to load balancer"

- name: Lock down load balancer
  hosts: load_balancer
  become: true
  serial: 1
  vars:
    bastion_host: "{{ groups['monitoring'][0] }}"
    bastion_ip: "{{ hostvars[bastion_host].ansible_host | default(bastion_host) }}"

  tasks:
    - name: Ensure UFW is installed
      package:
        name: ufw
        state: present

    - name: Reset UFW rules
      shell: ufw --force reset

    - name: Set default deny incoming
      ufw:
        direction: incoming
        policy: deny

    - name: Allow outgoing traffic
      ufw:
        direction: outgoing
        policy: allow

    - name: Allow SSH only from bastion
      ufw:
        rule: allow
        port: 22
        proto: tcp
        from_ip: "{{ bastion_ip }}"

    - name: Allow ports 60000-65000 from public
      ufw:
        rule: allow
        port: "60000:65000"
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled

- name: Wait before continuing to web servers
  hosts: localhost
  tasks:
    - pause:
        prompt: "Load balancer lock-down complete. Press ENTER to continue to web servers"

- name: Lock down web servers
  hosts: web
  become: true
  serial: 1
  vars:
    bastion_host: "{{ groups['monitoring'][0] }}"
    bastion_ip: "{{ hostvars[bastion_host].ansible_host | default(bastion_host) }}"
    loadbalancer_host: "{{ groups['load_balancer'][0] }}"
    loadbalancer_ip: "{{ hostvars[loadbalancer_host].ansible_host | default(loadbalancer_host) }}"

  tasks:
    - name: Ensure UFW is installed
      package:
        name: ufw
        state: present

    - name: Reset UFW rules
      shell: ufw --force reset

    - name: Set default deny incoming
      ufw:
        direction: incoming
        policy: deny

    - name: Allow outgoing traffic
      ufw:
        direction: outgoing
        policy: allow

    - name: Allow SSH only from bastion
      ufw:
        rule: allow
        port: 22
        proto: tcp
        from_ip: "{{ bastion_ip }}"

    - name: Allow port 80 only from load balancer
      ufw:
        rule: allow
        port: 80
        proto: tcp
        from_ip: "{{ loadbalancer_ip }}"

    - name: Enable UFW
      ufw:
        state: enabled
