---
- name: Add web and load balancer hosts to Nagios monitoring
  hosts: monitoring
  become: true
  vars:
    nagios_cfg_dir: /usr/local/nagios/etc/objects
    nagios_cfg_file: "{{ nagios_cfg_dir }}/monitored_hosts.cfg"

  tasks:
    - name: Generate Nagios host definitions for web and load balancer groups
      copy:
        dest: "{{ nagios_cfg_file }}"
        content: |
          {# Add web hosts #}
          {% for host in groups['web'] %}
          define host {
              use                     linux-server
              host_name               {{ host }}
              alias                   Web server {{ host }}
              address                 {{ hostvars[host].ansible_host | default(host) }}
              max_check_attempts      5
              check_period            24x7
              notification_interval   30
              notification_period     24x7
          }

          define service {
              use                     generic-service
              host_name               {{ host }}
              service_description     PING
              check_command           check_ping!100.0,20%!500.0,60%
          }

          define service {
              use                     generic-service
              host_name               {{ host }}
              service_description     SSH
              check_command           check_ssh
          }
          {% endfor %}

          {# Add load balancer hosts #}
          {% for host in groups['load_balancer'] %}
          define host {
              use                     linux-server
              host_name               {{ host }}
              alias                   Load balancer {{ host }}
              address                 {{ hostvars[host].ansible_host | default(host) }}
              max_check_attempts      5
              check_period            24x7
              notification_interval   30
              notification_period     24x7
          }

          define service {
              use                     generic-service
              host_name               {{ host }}
              service_description     PING
              check_command           check_ping!100.0,20%!500.0,60%
          }

          define service {
              use                     generic-service
              host_name               {{ host }}
              service_description     SSH
              check_command           check_ssh
          }
          {% endfor %}

    - name: Ensure monitored_hosts.cfg is included in nagios.cfg
      lineinfile:
        path: /usr/local/nagios/etc/nagios.cfg
        regexp: '^cfg_file={{ nagios_cfg_file }}$'
        line: "cfg_file={{ nagios_cfg_file }}"
        state: present

    - name: Verify Nagios configuration
      shell: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
      register: nagios_check
      ignore_errors: true

    - name: Show Nagios config test result
      debug:
        var: nagios_check.stdout_lines

    - name: Fail if Nagios config test failed
      fail:
        msg: "Nagios configuration check failed!"
      when: nagios_check.rc != 0

    - name: Reload Nagios
      service:
        name: nagios
        state: reloaded
