---
- name: Deploy existing Nagios backend check plugin
  hosts: monitoring
  become: true
  vars:
    nagios_plugin_dir: /usr/local/nagios/libexec
    nagios_cfg_dir: /usr/local/nagios/etc
    local_plugin_path:  nagios-plugin/host-monitor.py        # adjust to where you saved it
    local_backend_file: ./files/hosts.txt                     # adjust to where you saved it
    remote_plugin_path: "{{ nagios_plugin_dir }}/check_backends.py"
    remote_backend_file: "{{ nagios_cfg_dir }}/hosts.txt"

  tasks:
    - name: Copy host-monitor.py plugin
      copy:
        src: "{{ local_plugin_path }}"
        dest: "{{ remote_plugin_path }}"
        mode: '0755'

    - name: Copy host.txt file
      copy:
        src: "{{ local_backend_file }}"
        dest: "{{ remote_backend_file }}"
        mode: '0644'

    - name: Add check_backends command to commands.cfg
      blockinfile:
        path: "{{ nagios_cfg_dir }}/objects/commands.cfg"
        marker: "# {mark} ANSIBLE CHECK_BACKENDS"
        block: |
          define command {
              command_name    check_backends
              command_line    {{ remote_plugin_path }}
          }

    - name: Add backend service check to localhost.cfg
      blockinfile:
        path: "{{ nagios_cfg_dir }}/objects/localhost.cfg"
        marker: "# {mark} ANSIBLE BACKEND CHECK"
        block: |
          define service {
              use                     local-service
              host_name               localhost
              service_description     Backend Server Check
              check_command           check_backends
          }

    - name: Validate Nagios configuration
      shell: /usr/local/nagios/bin/nagios -v {{ nagios_cfg_dir }}/nagios.cfg
      register: nagios_check
      ignore_errors: true

    - name: Show Nagios validation result
      debug:
        var: nagios_check.stdout_lines

    - name: Fail if Nagios validation failed
      fail:
        msg: "Nagios configuration check failed!"
      when: nagios_check.rc != 0

    - name: Reload Nagios service
      service:
        name: nagios
        state: reloaded
