---
- name: Install Nagios Core from source
  hosts: monitoring
  become: true

  vars:
    nagios_version: "4.4.14"
    nagios_plugins_version: "2.4.12"
    apache_user: www-data

  tasks:
    - name: Install required packages
      apt:
        name:
          - autoconf
          - gcc
          - libc6 
          - make 
          - wget
          - unzip
          - apache2
          - php
          - libapache2-mod-php
          - libgd-dev
          - ufw
        state: present
        update_cache: yes

    - name: Install required packages part 2
      apt:
        name:
          - openssl 
          - libssl-dev
        state: present
        update_cache: yes

    - name: Install required packages for Nagios plugins
      apt:
        name:
          - libmcrypt-dev
          - bc
          - gawk
          - dc
          - build-essential
          - snmp
          - libnet-snmp-perl 
          - gettext
        state: present
        update_cache: yes

    - name: Download Nagios source
      get_url:
        url: "https://github.com/NagiosEnterprises/nagioscore/releases/download/nagios-{{ nagios_version }}/nagios-{{ nagios_version }}.tar.gz"
        dest: /tmp/nagioscore.tar.gz

    - name: Download Nagios plugins
      get_url:
        url: "https://github.com/nagios-plugins/nagios-plugins/releases/download/release-{{ nagios_plugins_version }}/nagios-plugins-{{ nagios_plugins_version }}.tar.gz"
        dest: /tmp/nagios-plugins.tar.gz
  
    - name: Extract Nagios
      unarchive:
        src: /tmp/nagioscore.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Extract Nagios Plugins
      unarchive:
        src: /tmp/nagios-plugins.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Nagios
      shell: |
        cd /tmp/nagios-{{ nagios_version }}
        ./configure /configure --with-httpd-conf=/etc/apache2/sites-enabled
        make all
        make install-groups-users
        usermod -a -G nagios www-data
        make install
        make install-daemoninit
        make install-commandmode
        make install-config
        make install-webconf
      args:
        executable: /bin/bash

    - name: Enable Apache rewrite module
      command: a2enmod rewrite
      notify: reload apache

    - name: Enable Apache cgi module
      command: a2enmod cgi
      notify: reload apache

    - name: Ensure Apache is enabled and running
      service:
        name: apache2
        enabled: yes
        state: started

    - name: Create Nagios web user
      shell: htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin nagiosadmin

    - name: Enable and start Nagios service
      service:
        name: nagios
        enabled: yes
        state: started

    - name: Compile and install Nagios Plugins
      shell: |
        cd /tmp/nagios-plugins-{{ nagios_plugins_version }}
        ./configure
        make
        make install
      args:
        executable: /bin/bash

    - name: Restart Nagios
      service:
        name: nagios
        state: restarted