---
- name: Install Nagios Core from source
  hosts: monitoring
  become: true

  vars:
    nagios_version: "4.4.14"
    nagios_plugins_version: "2.4.12"
    nagios_user: nagios
    nagios_group: nagcmd
    apache_user: www-data

  tasks:
    - name: Install required packages
      apt:
        name:
          - autoconf
          - gcc
          - make
          - unzip
          - apache2
          - apache2-utils
          - php
          - libapache2-mod-php
          - libgd-dev
          - libmcrypt-dev
          - libssl-dev
          - daemon
          - wget
          - build-essential
          - libtool
          - libjpeg-dev
          - libpng-dev
          - libperl-dev
          - libdbi-dev
        state: present
        update_cache: yes

    - name: Create Nagios user and group
      user:
        name: "{{ nagios_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Create nagcmd group
      group:
        name: "{{ nagios_group }}"

    - name: Add nagios and apache users to nagcmd group
      user:
        name: "{{ item }}"
        groups: "{{ nagios_group }}"
        append: yes
      loop:
        - "{{ nagios_user }}"
        - "{{ apache_user }}"

    - name: Download Nagios source
      get_url:
        url: "https://github.com/NagiosEnterprises/nagioscore/releases/download/nagios-{{ nagios_version }}/nagios-{{ nagios_version }}.tar.gz"
        dest: /tmp/nagios.tar.gz

    - name: Extract Nagios
      unarchive:
        src: /tmp/nagios.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Nagios
      shell: |
        cd /tmp/nagios-{{ nagios_version }}
        ./configure --with-command-group={{ nagios_group }}
        make all
        make install
        make install-init
        make install-commandmode
        make install-config
        make install-webconf
      args:
        executable: /bin/bash

    - name: Create Nagios web user
      shell: htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin nagiosadmin

    - name: Enable Apache modules and restart
      shell: |
        a2enmod cgi
        systemctl restart apache2
        systemctl enable apache2
      args:
        executable: /bin/bash

    - name: Enable Nagios service
      shell: |
        systemctl daemon-reexec
        systemctl enable nagios
        systemctl start nagios
      args:
        executable: /bin/bash

    - name: Add /usr/local/nagios/bin to system PATH
      copy:
        dest: /etc/profile.d/nagios.sh
        content: 'export PATH=$PATH:/usr/local/nagios/bin'
        mode: '0755'
