---
- name: Grant sudo access without password
  hosts: all
  become: yes

  vars:
    target_user: expensify

  tasks:
    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ target_user }}"
        state: present

    - name: Add user to sudo group
      ansible.builtin.user:
        name: "{{ target_user }}"
        groups: sudo
        append: yes

    - name: Allow passwordless sudo for user
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ target_user }}"
        content: "{{ target_user }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'
